use std::fs;
use std::fs::DirBuilder;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::json;

use crate::app::AppDesc;

use super::{App, Builder, BuilderError};

#[derive(Debug)]
pub struct CodegenParams<'py> {
    pub desc: &'py AppDesc<'py>,
}

pub struct CodegenResult {
    /// The path to the generated code directory.
    pub gen_dir: PathBuf,
}

#[derive(Debug, Serialize)]
struct ServiceData {
    name: String,
    import_path: Option<String>,
}

#[derive(Debug, Serialize)]
struct EndpointData {
    service_name: String,
    name: String,
    import_path: String,
}

#[derive(Debug, Serialize)]
struct GatewayData {
    encore_name: String,
    import_path: String,
    bind_name: String,
}

impl Builder<'_> {
    pub fn generate_code(&self, params: CodegenParams) -> Result<CodegenResult, BuilderError> {
        let files = self.codegen_data(&params)?;
        let gen_dir = self.app.root.join("encore_gen");
        write_gen_encore_dir(&gen_dir, &files)?;
        Ok(CodegenResult { gen_dir })
    }

    fn codegen_data(&self, params: &CodegenParams) -> Result<Vec<CodegenFile>, BuilderError> {
        let mut files = vec![];
        let meta = &params.desc.meta;

        // Build services data
        let services: Vec<ServiceData> = meta
            .svcs
            .iter()
            .map(|svc| ServiceData {
                name: svc.name.clone(),
                import_path: if svc.rel_path.is_empty() {
                    None
                } else {
                    Some(rel_path_to_import(&svc.rel_path))
                },
            })
            .collect();

        // Build endpoints data
        let endpoints: Vec<EndpointData> = meta
            .svcs
            .iter()
            .flat_map(|svc| {
                svc.rpcs.iter().map(|rpc| {
                    let import_path = rpc
                        .loc
                        .as_ref()
                        .map(|loc| {
                            // Convert pkg_path/filename to import path
                            let mut path = loc.pkg_path.clone();
                            if !path.is_empty() {
                                path.push('.');
                            }
                            // Remove .py extension from filename
                            let filename =
                                loc.filename.strip_suffix(".py").unwrap_or(&loc.filename);
                            path.push_str(filename);
                            path.replace('/', ".")
                        })
                        .unwrap_or_else(|| format!("{}.endpoints", svc.rel_path.replace('/', ".")));

                    EndpointData {
                        service_name: rpc.service_name.clone(),
                        name: rpc.name.clone(),
                        import_path,
                    }
                })
            })
            .collect();

        // Build gateways data
        let gateways: Vec<GatewayData> = meta
            .gateways
            .iter()
            .filter_map(|gw| {
                // Only include explicit gateways
                gw.explicit.as_ref().map(|explicit| {
                    let import_path =
                        format!("{}.gateway", explicit.service_name.replace('/', "."));
                    GatewayData {
                        encore_name: gw.encore_name.clone(),
                        import_path,
                        bind_name: "gateway".to_string(),
                    }
                })
            })
            .collect();

        // Generate combined main entrypoint
        let ctx = &json!({
            "services": services,
            "endpoints": endpoints,
            "gateways": gateways,
        });

        let main = self.entrypoint_combined_main.render(&self.reg, ctx)?;
        files.push(CodegenFile {
            path: PathBuf::from("internal")
                .join("entrypoints")
                .join("combined")
                .join("main.py"),
            contents: main,
        });

        // Generate __init__.py files to make the directories Python packages
        files.push(CodegenFile {
            path: PathBuf::from("__init__.py"),
            contents: "# Generated by Encore\n".to_string(),
        });
        files.push(CodegenFile {
            path: PathBuf::from("internal").join("__init__.py"),
            contents: "# Generated by Encore\n".to_string(),
        });
        files.push(CodegenFile {
            path: PathBuf::from("internal")
                .join("entrypoints")
                .join("__init__.py"),
            contents: "# Generated by Encore\n".to_string(),
        });
        files.push(CodegenFile {
            path: PathBuf::from("internal")
                .join("entrypoints")
                .join("combined")
                .join("__init__.py"),
            contents: "# Generated by Encore\n".to_string(),
        });

        Ok(files)
    }
}

/// Converts a relative file path to a Python import path.
fn rel_path_to_import(rel_path: &str) -> String {
    rel_path.replace('/', ".").replace('\\', ".")
}

#[derive(Debug)]
pub struct CodegenFile {
    pub path: PathBuf,
    pub contents: String,
}

fn write_gen_encore_dir(base_dir: &Path, files: &[CodegenFile]) -> Result<(), BuilderError> {
    for f in files {
        if f.path.is_absolute() {
            return Err(BuilderError::Internal(anyhow::anyhow!(
                "path {:?} is not relative to the encore_gen folder",
                f.path
            )));
        }

        let file_path = base_dir.join(&f.path);

        // Create the parent of the file, if needed
        if let Some(parent) = file_path.parent() {
            DirBuilder::new()
                .recursive(true)
                .create(parent)
                .map_err(BuilderError::GenerateCode)?;
        }

        let file = fs::File::create(file_path).map_err(BuilderError::GenerateCode)?;
        let mut buf = std::io::BufWriter::new(file);
        buf.write_all(f.contents.as_bytes())
            .map_err(BuilderError::GenerateCode)?;
        buf.flush().map_err(BuilderError::GenerateCode)?;
    }

    Ok(())
}
