"""
Application metadata for Encore applications.

This module provides access to metadata about the running Encore application,
including environment information, build details, and deployment data.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Literal

from encoredev.internal import RT


class EnvironmentType(str, Enum):
    """Describes what type of environment the application is running in."""

    PRODUCTION = "production"
    """A production environment."""

    DEVELOPMENT = "development"
    """A long-lived cloud-hosted, non-production environment, such as test environments, or local development."""

    EPHEMERAL = "ephemeral"
    """A short-lived cloud-hosted, non-production environment, such as preview environments."""

    TEST = "test"
    """When running automated tests."""


class CloudProvider(str, Enum):
    """Describes what cloud provider the application is running in."""

    AWS = "aws"
    """Amazon Web Services."""

    GCP = "gcp"
    """Google Cloud Platform."""

    AZURE = "azure"
    """Microsoft Azure."""

    ENCORE = "encore"
    """Encore Cloud."""

    LOCAL = "local"
    """Local development."""


@dataclass(frozen=True)
class HostedService:
    """Information about a hosted service."""

    name: str
    """The name of the service."""


@dataclass(frozen=True)
class EnvironmentMeta:
    """Describes the environment the Encore application is running in."""

    name: str
    """The name of environment that this application. For local development it is "local"."""

    type: EnvironmentType
    """The type of environment this application is running in. For local development it is "development"."""

    cloud: CloudProvider
    """The cloud this is running in. For local development it is "local"."""


@dataclass(frozen=True)
class BuildMeta:
    """Information about the build that formed the running application."""

    revision: str
    """The git commit that formed the base of this build."""

    uncommitted_changes: bool
    """Whether there were uncommitted changes on top of the commit."""


@dataclass(frozen=True)
class DeployMeta:
    """Information about the deployment of the running application."""

    id: str
    """The unique id of the deployment. Generated by the Encore Platform."""

    hosted_services: dict[str, HostedService]
    """The services hosted by this deployment, keyed by the service name."""


@dataclass(frozen=True)
class AppMeta:
    """Describes the running Encore application."""

    app_id: str
    """
    The Encore application ID. If the application is not linked to the Encore platform
    this will be an empty string. To link to the Encore platform run `encore app link`
    from your terminal in the root directory of the Encore app.
    """

    api_base_url: str
    """
    The base URL which can be used to call the API of this running application.

    For local development it is "http://localhost:<port>", typically "http://localhost:4000".

    If a custom domain is used for this environment it is returned here, but note that
    changes only take effect at the time of deployment while custom domains can be
    updated at any time.
    """

    environment: EnvironmentMeta
    """Information about the environment the app is running in."""

    build: BuildMeta
    """Information about the build."""

    deploy: DeployMeta
    """Information about the deployment."""


# Cached app metadata
_cached_meta: AppMeta | None = None


def _env_type(rt_type: str) -> EnvironmentType:
    """Convert runtime environment type to EnvironmentType enum."""
    mapping = {
        "production": EnvironmentType.PRODUCTION,
        "development": EnvironmentType.DEVELOPMENT,
        "ephemeral": EnvironmentType.EPHEMERAL,
        "test": EnvironmentType.TEST,
    }
    return mapping.get(rt_type, EnvironmentType.DEVELOPMENT)


def _cloud_provider(rt_cloud: str) -> CloudProvider:
    """Convert runtime cloud provider to CloudProvider enum."""
    mapping = {
        "aws": CloudProvider.AWS,
        "gcp": CloudProvider.GCP,
        "azure": CloudProvider.AZURE,
        "encore": CloudProvider.ENCORE,
        "local": CloudProvider.LOCAL,
    }
    return mapping.get(rt_cloud, CloudProvider.LOCAL)


def app_meta() -> AppMeta:
    """
    Returns metadata about the running Encore application.

    The metadata is cached and is the same object each call,
    and therefore must not be modified by the caller.
    """
    global _cached_meta

    if _cached_meta is None:
        rt = RT.app_meta()
        hosted_services = {
            name: HostedService(name=svc.get("name", name))
            for name, svc in rt.get("deploy", {}).get("hosted_services", {}).items()
        }

        _cached_meta = AppMeta(
            app_id=rt.get("app_id", ""),
            api_base_url=rt.get("api_base_url", "http://localhost:4000"),
            environment=EnvironmentMeta(
                name=rt.get("environment", {}).get("name", "local"),
                type=_env_type(rt.get("environment", {}).get("type", "development")),
                cloud=_cloud_provider(rt.get("environment", {}).get("cloud", "local")),
            ),
            build=BuildMeta(
                revision=rt.get("build", {}).get("revision", ""),
                uncommitted_changes=rt.get("build", {}).get("uncommitted_changes", False),
            ),
            deploy=DeployMeta(
                id=rt.get("deploy", {}).get("id", ""),
                hosted_services=hosted_services,
            ),
        )

    return _cached_meta


__all__ = [
    "app_meta",
    "AppMeta",
    "BuildMeta",
    "CloudProvider",
    "DeployMeta",
    "EnvironmentMeta",
    "EnvironmentType",
    "HostedService",
]
